[database]
url = "mssql://abcabcabc:pass123123@100.10.0.00:1433/dbnname"


[paths]
source = "D:\\OJT\\SourcePathBackup"
destination = "D:\\OJT\\DestPath"
jar_file = "D:\\DiscrepancyLogs\\Discrepancy_Utility.jar"